# Generated by Django 3.2 on 2021-04-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id_str', models.CharField(max_length=40)),
                ('svg', models.TextField()),
            ],
        ),
    ]
