import logging
import tweepy
import sys, os
from replytree import ReplyTree, extract_id
import time
import re

# auth = tweepy.OAuthHandler("VlVMy496M1Gtj6dWbCXEFmSDu",
#     "25hmkRpCYIR7b6xbP8wottv2D2uo9u7gSIh5HoFKDb6KiaLDw9")
# auth.set_access_token("4115845397-n6WRHuCGX84MlFyzOyTMtn5F50qAsX4Q3JeO2yB",
#     "ZxmzIiZAwKl6IZsrRAi0ejMIHVKm8C45ahB906EkmKs0n")

try:
    tweet_url = sys.argv[1]
except:
    print("Example usage: ")
    print("python twitter_tree.py \"https://twitter.com/username/status/0000000000000000000\"")
    sys.exit(1)

# 1377033260425961472 -- hyamarket books (small) 
# 1376545600427134979 -- john pfaff (large)
# origin_id = extract_id(tweet_url)
# logging.info(f"Creating Tree from Tweet {origin_id}")
# tt = ReplyTree(origin_id)
# tt.populate_tree()
raw_svg = """<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.40.1 (20161225.0304)
 -->
<!-- Pages: 1 -->
<svg width="766pt" height="240pt"
 viewBox="0.00 0.00 766.00 240.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 236)">
<polygon fill="#f3eff6" stroke="transparent" points="-4,4 -4,-236 762,-236 762,4 -4,4"/>
<!-- 1383432071415173127 -->
<g id="node1" class="node">
<title>1383432071415173127</title>
<path fill="#d3eaee" stroke="#000000" d="M544,-232C544,-232 187,-232 187,-232 181,-232 175,-226 175,-220 175,-220 175,-146 175,-146 175,-140 181,-134 187,-134 187,-134 544,-134 544,-134 550,-134 556,-140 556,-146 556,-146 556,-220 556,-220 556,-226 550,-232 544,-232"/>
<text text-anchor="start" x="326" y="-213.8" font-family="Times,serif" font-weight="bold" font-size="14.00" fill="#000000">@jbrand07</text>
<text text-anchor="start" x="395" y="-213.8" font-family="Times,serif" font-size="14.00" fill="#000000"> ◊</text>
<text text-anchor="start" x="187.5" y="-191.8" font-family="Times,serif" font-size="14.00" fill="#000000">400 cases vacated because an officer stole evidence and planted</text>
<text text-anchor="start" x="287.5" y="-176.8" font-family="Times,serif" font-size="14.00" fill="#000000">evidence in Fairfax County.</text>
<text text-anchor="start" x="303.5" y="-145" font-family="Times,serif" font-size="14.00" fill="#000000">https://t.co/I1aregy9jF</text>
<polygon fill="#000000" stroke="#000000" points="183.5,-206 183.5,-206 548.5,-206 548.5,-206 183.5,-206"/>
</g>
<!-- 1383448224896225296 -->
<g id="node2" class="node">
<title>1383448224896225296</title>
<path fill="#fff1e6" stroke="#000000" d="M331,-75C331,-75 12,-75 12,-75 6,-75 0,-69 0,-63 0,-63 0,-35 0,-35 0,-29 6,-23 12,-23 12,-23 331,-23 331,-23 337,-23 343,-29 343,-35 343,-35 343,-63 343,-63 343,-69 337,-75 331,-75"/>
<text text-anchor="start" x="117" y="-56.8" font-family="Times,serif" font-weight="bold" font-size="14.00" fill="#000000">@Paulkdougherty</text>
<text text-anchor="start" x="12.5" y="-34.8" font-family="Times,serif" font-size="14.00" fill="#000000">Is it me, or is this guy in the picture dislodging a wedgy?</text>
<polygon fill="#000000" stroke="#000000" points="8.5,-49 8.5,-49 335.5,-49 335.5,-49 8.5,-49"/>
</g>
<!-- 1383432071415173127&#45;&gt;1383448224896225296 -->
<g id="edge1" class="edge">
<title>1383432071415173127&#45;&gt;1383448224896225296</title>
<path fill="none" stroke="#000000" d="M294.3631,-133.8642C268.8565,-116.2463 240.7761,-96.8505 217.9063,-81.0538"/>
<polygon fill="#000000" stroke="#000000" points="219.6298,-77.9905 209.4126,-75.187 215.6515,-83.7502 219.6298,-77.9905"/>
</g>
<!-- 1383443419419209731 -->
<g id="node3" class="node">
<title>1383443419419209731</title>
<path fill="#dfe7fd" stroke="#000000" d="M746,-98C746,-98 373,-98 373,-98 367,-98 361,-92 361,-86 361,-86 361,-12 361,-12 361,-6 367,0 373,0 373,0 746,0 746,0 752,0 758,-6 758,-12 758,-12 758,-86 758,-86 758,-92 752,-98 746,-98"/>
<text text-anchor="start" x="514" y="-79.8" font-family="Times,serif" font-weight="bold" font-size="14.00" fill="#000000">@DogsDadBod</text>
<text text-anchor="start" x="373.5" y="-57.8" font-family="Times,serif" font-size="14.00" fill="#000000">If Descano hadn&#39;t been elected Commonwealth Attorney here, it is</text>
<text text-anchor="start" x="408" y="-42.8" font-family="Times,serif" font-size="14.00" fill="#000000">entirely possible this never would have been revealed.</text>
<text text-anchor="start" x="477" y="-11" font-family="Times,serif" font-size="14.00" fill="#000000">Elections have consequences.</text>
<polygon fill="#000000" stroke="#000000" points="369.5,-72 369.5,-72 750.5,-72 750.5,-72 369.5,-72"/>
</g>
<!-- 1383432071415173127&#45;&gt;1383443419419209731 -->
<g id="edge2" class="edge">
<title>1383432071415173127&#45;&gt;1383443419419209731</title>
<path fill="none" stroke="#000000" d="M436.6369,-133.8642C450.7389,-124.1236 465.6278,-113.8396 479.9878,-103.9208"/>
<polygon fill="#000000" stroke="#000000" points="482.1329,-106.693 488.3717,-98.1298 478.1545,-100.9333 482.1329,-106.693"/>
</g>
</g>
</svg>"""

# add in links (username links to profile, tweet body links to status)
username_blocks = [(m.start(), m.end()) for m in re.finditer('<text .*>@.*</text>', raw_svg)]
id_blocks = [(m.start()+5, m.end()-4) for m in re.finditer('<!-- [0-9]* -->', raw_svg)]
text_blocks = [(m.start(), m.end()-9) for m in re.finditer('<text (.|\n)*?<polygon', raw_svg)]

user_linked_svg = ""
last_index = 0
for (u_start,u_end), (i_start,i_end), (t_start,t_end) in zip(username_blocks, id_blocks, text_blocks):
    # locate the actual username in the username block
    m = re.search('@.*</', raw_svg[u_start:u_end])
    uname = raw_svg[u_start:u_end][m.start()+1:m.end()-2]

    # get id
    tweet_id = raw_svg[i_start:i_end]

    # add in the links to the raw svg
    # link username to profile
    user_linked_svg += raw_svg[last_index:u_start] + f'<a href="https://twitter.com/{uname}" target="_blank" rel="noopener noreferrer">'
    user_linked_svg += raw_svg[u_start:u_end] + '</a>'

    # link text to tweet
    user_linked_svg += f'<a href="https://twitter.com/{uname}/status/{tweet_id}" target="_blank" rel="noopener noreferrer">'
    user_linked_svg += raw_svg[u_end:t_end] + '</a>'

    last_index = t_end

user_linked_svg += raw_svg[last_index:]

with open("test.svg", "w") as f:
    f.write(user_linked_svg)

